export const SERVER_URL = process.env.SERVER_URL || "http://localhost:9000";
export const countries = [
  "	Albania		",
  "	Algeria		",
  "	Argentina		",
  "	Australia		",
  "	Austria		",
  "	Azerbaijan		",
  "	Bangladesh		",
  "	Belarus		",
  "	Belgium		",
  "	Bolivia		",
  "	Bosnia and Herzegovina		",
  "	Botswana		",
  "	Brazil		",
  "	Brunei		",
  "	Bulgaria		",
  "	Cambodia		",
  "	Canada		",
  "	Chile		",
  "	China		",
  "	Colombia		",
  "	Costa Rica		",
  "	Croatia		",
  "	Cyprus		",
  "	Czech Republic		",
  "	Côte D'Ivoire		",
  "	Denmark		",
  "	Dominican Republic		",
  "	Ecuador		",
  "	Egypt		",
  "	El Salvador		",
  "	Estonia		",
  "	Finland		",
  "	France		",
  "	Georgia		",
  "	Germany		",
  "	Ghana		",
  "	Greece		",
  "	Guadeloupe		",
  "	Guam		",
  "	Guatemala		",
  "	Honduras		",
  "	Hong Kong		",
  "	Hungary		",
  "	Iceland		",
  "	India		",
  "	Indonesia		",
  "	Iraq		",
  "	Ireland		",
  "	Israel		",
  "	Italy		",
  "	Jamaica		",
  "	Japan		",
  "	Jordan		",
  "	Kazakhstan		",
  "	Kenya		",
  "	Kosovo		",
  "	Kuwait		",
  "	Kyrgyzstan		",
  "	Latvia		",
  "	Lithuania		",
  "	Malawi		",
  "	Malaysia		",
  "	Mexico		",
  "	Moldova		",
  "	Mongolia		",
  "	Morocco		",
  "	Mozambique		",
  "	Myanmar		",
  "	Namibia		",
  "	Nepal		",
  "	Netherlands		",
  "	New Zealand		",
  "	Nicaragua		",
  "	Nigeria		",
  "	North Macedonia		",
  "	Norway		",
  "	Pakistan		",
  "	Panama		",
  "	Paraguay		",
  "	Peru		",
  "	Philippines		",
  "	Poland		",
  "	Portugal		",
  "	Puerto Rico		",
  "	Romania		",
  "	Russia		",
  "	Rwanda		",
  "	Réunion		",
  "	Saudi Arabia		",
  "	Serbia		",
  "	Singapore		",
  "	Slovakia		",
  "	Slovenia		",
  "	South Africa		",
  "	South Korea		",
  "	Spain		",
  "	Sri Lanka		",
  "	Sweden		",
  "	Switzerland		",
  "	Taiwan		",
  "	Tanzania		",
  "	Thailand		",
  "	Trinidad & Tobago		",
  "	Tunisia		",
  "	Turkey		",
  "	USA		",
  "	Uganda		",
  "	Ukraine		",
  "	United Arab Emirates		",
  "	United Kingdom		",
  "	Uruguay		",
  "	Uzbekistan		",
  "	Venezuela		",
  "	Vietnam		",
  "	Zambia		",
  "	Zimbabwe		",
].map((country) => country.trim());
